name: Build and Test

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
    - name: Set up environment file
      run: echo "$ENV_FILE_SECRET" > .env
    - name: Build
      run: go build -v ./...
    - name: Install godotenv
      run: go get github.com/joho/godotenv/cmd/godotenv
    - name: Run tests
      run: |
        godotenv -f ./.env go test ./internal/... -cover
